### PR TITLE
miniaudio audio backend support

### PR DESCRIPTION
**Pull request by a740g**
Hi @mkilgore,

I am opening this PR like we discussed on Discord. Please let me know if you need my help with anything.

### CODE REVIEW

**Comment by mkilgore** [comment]
I'm starting to review this but it seems fine, I already basically reviewed it once :) I think all that's probably left for your changes is to just make a list of any issues we should make after it gets merged. We'll want one for the potential `_SNDRAW` improvements, I'm not sure if there were any others we identified, I'll have to go back over my comments.

Beyond that I'm going to start work on making it possible to fallback to the old backend if wanted, hopefully that goes smoothly. If I get that working you could either pull those changes into this PR, or I could make a new PR for the whole thing, up to you :)

**Comment by a740g** [comment]
> I think all that's probably left for your changes is to just make a list of any issues we should make after it gets merged. We'll want one for the potential _SNDRAW improvements, I'm not sure if there were any others we identified

Agreed. We'll also have to make some changes / updates to the wiki and might need to pull in @RhoSigma-QB64 for help. Subtle changes in `_MEMSOUND` and `_SNDOPEN` (extra format and streaming support) behavior need to be documented. 

> If I get that working you could either pull those changes into this PR, or I could make a new PR for the whole thing, up to you :)

Like I said, I am a `PR noob`. I am just learning and picking up stuff as I go. So, I'll leave this to you. I'd actually prefer whichever is easier. 😉

I also have some minor but important bugfixes that I've identified after opening the PR (mostly to do with fixing looping issues in our format data sources). I'll push the fixes to my repo soon. How do we get this new stuff added? Or do I need to create a new PR for that?

**Comment by mkilgore** [comment]
> Agreed. We'll also have to make some changes / updates to the wiki and might need to pull in @RhoSigma-QB64 for help. Subtle changes in `_MEMSOUND` and `_SNDOPEN` (extra format and streaming support) behavior need to be documented.

Yes that makes sense, but we can likely handle that :) I have a membership to the Wiki and we can get you one as well if you don't. It shouldn't be to hard to add the relevant information on the pages and clarify what versions of QB64PE (and/or what sound backend) is required.

> Like I said, I am a `PR noob`. I am just learning and picking up stuff as I go. So, I'll leave this to you. I'd actually prefer whichever is easier. 😉
> 
> I also have some minor but important bugfixes that I've identified after opening the PR (mostly to do with fixing looping issues in our format data sources). I'll push the fixes to my repo soon. How do we get this new stuff added? Or do I need to create a new PR for that?

It will probably be easier for me to just make a new PR afterwards, then it's one less thing you'll have to do :) But leave this one open and continue to just push any changes you have to your branch as you were before. Anything in that branch will get added to this PR automatically.

**Comment by RhoSigma-QB64** [comment]
As for the needed Wiki changes, just go for it adding the technical info required, Don't worry about any format layout things, as I can always look over the pages and bring it into the right shape afterwards.

**Comment by a740g** [comment]
Closing this PR as https://github.com/QB64-Phoenix-Edition/QB64pe/pull/143 supersedes this.

**Pull request closed without merging**
