### PR TITLE
Swap to New Load Dialog

### PR DESCRIPTION
**Pull request by SteveMcNeill**
Without IDE toggle yet between old and new dialogs, for testing purposes and comments.

### CODE REVIEW

**Comment by a740g** [comment]
`source/qb64pe.bas: 13,839 additions, 13,837 deletions not shown because the diff is too large. Please use a local Git client to view these changes.`
@SteveMcNeill I think you turned off the `Keywords in CAPTITALS` option unchecked by accident. :)

**Comment by SteveMcNeill** [comment]
> 

Aye.  QB64 doesn't come with the "Keywords in CAPITALS" turned on, so I just didn't think about clicking that option. Maybe we should start shipping with that option clicked on so I won't do this with every Xth commit.  ;)

**Comment by a740g** [comment]
> Maybe we should start shipping with that option clicked on so I won't do this with every Xth commit. ;)

I agree with you on this one. Eventhough I prefer camel-casing, I think that is more susceptible to change. For people lke me who like camel-case, they can always enable the IDE option and it will remember it.

**Comment by SteveMcNeill** [comment]
Closing to resubmit with Capitalization issues.

**Pull request closed without merging**
